#!/bin/sh
# install.sh — build one pending generation from small resource primitives.

hw_install_assets() {
    _hia_moddir=$1; _hia_name=$2; _hia_gen=$3
    _hia_path=$(hw_module_get "$_hia_moddir" "$_hia_name" path)
    [ -d "$_hia_path/assets" ] || return 0
    for _hia_item in "$_hia_path/assets"/*; do
        [ -e "$_hia_item" ] || [ -L "$_hia_item" ] || continue
        HOMEWORLD_MODULE_ROOT="$_hia_path" hw_asset_add "$_hia_item" "$(basename "$_hia_item")" "$_hia_gen" "$_hia_name"
    done
}

hw_command_add() {
    _hca_source=$1; _hca_name=$2; _hca_gen=$3; _hca_module=$4
    hw_validate_name "$_hca_name" "command name"
    _hca_dest="$_hca_gen/commands/$_hca_module/$_hca_name"
    if [ -d "$_hca_source" ]; then
        [ -f "$_hca_source/run" ] || hw_die "command $_hca_name is missing an executable run file"
        [ -x "$_hca_source/run" ] || hw_die "command $_hca_name run file is not executable"
        hw_copy_resource "$_hca_source" "$_hca_dest"
    else
        [ -f "$_hca_source" ] && [ -x "$_hca_source" ] || hw_die "command source must be an executable file or command directory"
        mkdir -p "$_hca_dest"
        cp "$_hca_source" "$_hca_dest/run" || hw_die "could not stage command"
        chmod +x "$_hca_dest/run"
    fi
    [ ! -e "$_hca_gen/bin/$_hca_name" ] || hw_die "command name conflict: $_hca_name"
    hw_make_launcher "$_hca_gen/bin/$_hca_name" "$_hca_dest"
}

hw_install_commands() {
    _hic_moddir=$1; _hic_name=$2; _hic_gen=$3
    _hic_path=$(hw_module_get "$_hic_moddir" "$_hic_name" path)
    [ -d "$_hic_path/commands" ] || return 0
    for _hic_item in "$_hic_path/commands"/*; do
        [ -d "$_hic_item" ] || continue
        hw_command_add "$_hic_item" "$(basename "$_hic_item")" "$_hic_gen" "$_hic_name"
    done
}

hw_make_launcher() {
    _hml_launcher=$1; _hml_dir=$2
    mkdir -p "$(dirname "$_hml_launcher")"
    {
        printf '#!/bin/sh\n'
        printf '# Generated by Homeworld.\n'
        printf 'export HOMEWORLD_COMMAND_DIR=%s\n' "$(printf "'%s'" "$(printf '%s' "$_hml_dir" | sed "s/'/'\\\\''/g")")"
        printf 'exec "$HOMEWORLD_COMMAND_DIR/run" "$@"\n'
    } > "$_hml_launcher"
    chmod +x "$_hml_launcher"
}

hw_install_packages() {
    _hip_provider=$1; _hip_file=$2
    [ -f "$_hip_file" ] || return 0
    _hip_packages=$(grep -v '^[[:space:]]*$' "$_hip_file" | grep -v '^[[:space:]]*#' | sort -u)
    [ -n "$_hip_packages" ] || return 0
    hw_log "Planning packages through $_hip_provider:"
    printf '%s\n' "$_hip_packages" | while IFS= read -r _hip_package; do hw_log "  $_hip_package"; done
    _hip_args=$(printf '%s\n' "$_hip_packages" | tr '\n' ' ')
    case "$_hip_provider" in
        pacman) sudo pacman -S --needed --noconfirm $_hip_args ;;
        apt) sudo apt-get install -y $_hip_args ;;
        dnf) sudo dnf install -y $_hip_args ;;
        brew) brew install $_hip_args ;;
        *) hw_die "unknown package provider: $_hip_provider" ;;
    esac
}

# hw_install_carry_forward prev_gen new_gen module_name
# Reuse a module's resources from the previous generation verbatim instead of
# re-running install.sh. Only called when the module's declared
# HOMEWORLD_MODULE_VERSION is unchanged from the last successful install, so
# this never has to guess whether anything drifted (a floating git ref, a
# live hardware probe) — the module author's version bump is the only signal
# that matters.
hw_install_carry_forward() {
    _hicf_prev=$1; _hicf_gen=$2; _hicf_name=$3

    # Assets, config, and commands are already stored per-module inside the
    # generation directory — a plain copy carries them forward intact.
    for _hicf_kind in assets config commands; do
        [ -d "$_hicf_prev/$_hicf_kind/$_hicf_name" ] || continue
        mkdir -p "$_hicf_gen/$_hicf_kind"
        rm -rf "$_hicf_gen/$_hicf_kind/$_hicf_name"
        cp -R "$_hicf_prev/$_hicf_kind/$_hicf_name" "$_hicf_gen/$_hicf_kind/$_hicf_name"
    done

    # Regenerate command launchers so they point at this generation's copy.
    if [ -d "$_hicf_gen/commands/$_hicf_name" ]; then
        for _hicf_cmd_dir in "$_hicf_gen/commands/$_hicf_name"/*; do
            [ -d "$_hicf_cmd_dir" ] || continue
            hw_make_launcher "$_hicf_gen/bin/$(basename "$_hicf_cmd_dir")" "$_hicf_cmd_dir"
        done
    fi

    # Repository manifest entries this module owns: copy the resolved
    # source/sha verbatim (do not re-resolve the ref — that would silently
    # start tracking upstream again even though the version didn't bump) and
    # re-link the checkout into the new generation so it stays GC-reachable.
    _hicf_manifest_src=$(hw_repo_manifest_dir "$_hicf_prev")
    if [ -d "$_hicf_manifest_src" ]; then
        for _hicf_entry in "$_hicf_manifest_src"/*; do
            [ -d "$_hicf_entry" ] || continue
            [ "$(cat "$_hicf_entry/module" 2>/dev/null)" = "$_hicf_name" ] || continue
            _hicf_ns=$(basename "$_hicf_entry")
            _hicf_manifest_dst=$(hw_repo_manifest_dir "$_hicf_gen")
            mkdir -p "$_hicf_manifest_dst"
            [ -f "$_hicf_manifest_dst/schema-version" ] || hw_schema_write "$_hicf_manifest_dst"
            rm -rf "$_hicf_manifest_dst/$_hicf_ns"
            cp -R "$_hicf_entry" "$_hicf_manifest_dst/$_hicf_ns"
            _hicf_id=$(cat "$_hicf_manifest_dst/$_hicf_ns/source-id")
            _hicf_sha=$(cat "$_hicf_manifest_dst/$_hicf_ns/sha")
            hw_repo_gen_link "$_hicf_ns" "$_hicf_id" "$_hicf_sha" "$_hicf_gen"
        done
    fi

    # Managed links (repo/config/asset/state link) this module recorded.
    # Their directory key is a hash of dest|type|id|module alone, so a
    # verbatim copy lands under the same key it would if re-declared today.
    _hicf_links_src=$(hw_managed_links_dir "$_hicf_prev")
    if [ -d "$_hicf_links_src" ]; then
        _hicf_links_dst=$(hw_managed_links_dir "$_hicf_gen")
        for _hicf_link in "$_hicf_links_src"/*; do
            [ -d "$_hicf_link" ] || continue
            [ "$(cat "$_hicf_link/module" 2>/dev/null)" = "$_hicf_name" ] || continue
            mkdir -p "$_hicf_links_dst"
            [ -f "$_hicf_links_dst/schema-version" ] || hw_schema_write "$_hicf_links_dst"
            rm -rf "$_hicf_links_dst/$(basename "$_hicf_link")"
            cp -R "$_hicf_link" "$_hicf_links_dst/$(basename "$_hicf_link")"
        done
        hw_projection_invalidate "$_hicf_gen"
    fi
}

# hw_install_module_prev_version prev_gen module_name
# Look up what version was recorded for this module the last time a
# generation was fully built and activated. Empty if unknown.
hw_install_module_prev_version() {
    _himpv_prev=$1; _himpv_name=$2
    _himpv_file="$_himpv_prev/.homeworld/module-versions"
    [ -f "$_himpv_file" ] || return 0
    while IFS="$(printf '\t')" read -r _himpv_n _himpv_v; do
        [ "$_himpv_n" = "$_himpv_name" ] && printf '%s' "$_himpv_v" && return 0
    done < "$_himpv_file"
}

hw_install_module() {
    _him_moddir=$1; _him_name=$2; _him_gen=$3; _him_platform=$4; _him_distro=$5; _him_force=${6:-0}
    _him_path=$(hw_module_get "$_him_moddir" "$_him_name" path)

    # A module only participates in cache-skip if it declares a version. This
    # keeps the behavior strictly opt-in: a module that never sets
    # HOMEWORLD_MODULE_VERSION is always run, exactly like before this
    # feature existed.
    if [ "$_him_force" != "1" ]; then
        _him_version=$(hw_module_get "$_him_moddir" "$_him_name" version)
        if [ -n "$_him_version" ] && [ -L "$(hw_current)" ]; then
            _him_prev=$(readlink "$(hw_current)")
            _him_prev_version=$(hw_install_module_prev_version "$_him_prev" "$_him_name")
            if [ -n "$_him_prev_version" ] && [ "$_him_prev_version" = "$_him_version" ]; then
                hw_log "$(printf '  %sUP TO DATE%s  %s (version %s unchanged)' "$_HW_C_OK" "$_HW_C_RST" "$_him_name" "$_him_version")"
                hw_install_carry_forward "$_him_prev" "$_him_gen" "$_him_name"
                return 0
            fi
        fi
    fi

    hw_log "  installing $_him_name..."
    hw_install_assets "$_him_moddir" "$_him_name" "$_him_gen"
    hw_install_commands "$_him_moddir" "$_him_name" "$_him_gen"
    _him_script="$_him_path/install.sh"
    [ -f "$_him_script" ] || return 0
    _him_self_bin=${HW_SELF_BIN:-}
    HOMEWORLD_MODULE_ROOT="$_him_path" \
    HOMEWORLD_MODULE_NAME="$_him_name" \
    HOMEWORLD_PLATFORM="$_him_platform" \
    HOMEWORLD_DISTRO="$_him_distro" \
    HOMEWORLD_ROOT="$(hw_current)" \
    HOMEWORLD_BIN="$(hw_current)/bin" \
    HOMEWORLD_TARGET="$_him_gen" \
    HOMEWORLD_TARGET_BIN="$_him_gen/bin" \
    PATH="${_him_self_bin:+$_him_self_bin:}$_him_gen/bin:$PATH" \
        sh "$_him_script" || hw_die "install.sh failed for module $_him_name" \
            "The pending generation was not activated."
}
