#!/bin/sh
# install.sh — the module installation pipeline.
#
# Each module is installed in dependency order. The pipeline is:
#   assets → commands → packages → install.sh (post-install hook)
# Commands from already-installed modules are on PATH by the time each
# module's install.sh runs, so transitive deps can provide tools.

# hw_install_assets moddir name gen_path
# Copy module's assets/ tree into the generation, namespaced by module name.
hw_install_assets() {
    _hia_moddir="$1"
    _hia_name="$2"
    _hia_gen="$3"

    _hia_path=$(hw_module_get "$_hia_moddir" "$_hia_name" "path")
    _hia_src="$_hia_path/assets"
    _hia_dest="$_hia_gen/assets/$_hia_name"

    # No assets directory is fine — many modules only provide commands
    [ -d "$_hia_src" ] || return 0

    mkdir -p "$_hia_dest"
    cp -r "$_hia_src/." "$_hia_dest/"
}

# hw_install_commands moddir name gen_path
# Copy each command directory and generate a launcher in gen_path/bin/.
hw_install_commands() {
    _hic_moddir="$1"
    _hic_name="$2"
    _hic_gen="$3"

    _hic_path=$(hw_module_get "$_hic_moddir" "$_hic_name" "path")
    _hic_cmd_src="$_hic_path/commands"

    [ -d "$_hic_cmd_src" ] || return 0

    for _hic_cmd_dir in "$_hic_cmd_src"/*/; do
        [ -d "$_hic_cmd_dir" ] || continue
        _hic_cmd_name=$(basename "$_hic_cmd_dir")

        # Validate command directory name
        _hic_name_bad=$(printf '%s' "$_hic_cmd_name" | tr -d 'a-z0-9._-')
        _hic_first_bad=$(printf '%s' "$_hic_cmd_name" | cut -c1 | tr -d 'a-z0-9')
        if [ -n "$_hic_name_bad" ] || [ -n "$_hic_first_bad" ]; then
            hw_die "invalid command name '$_hic_cmd_name' in module '$_hic_name'" \
                   "Command directory names must match [a-z0-9][a-z0-9._-]*."
        fi

        # Require an executable run file
        if [ ! -f "$_hic_cmd_dir/run" ]; then
            hw_die "command '$_hic_cmd_name' in module '$_hic_name' is missing a run file" \
                   "Create an executable file at commands/$_hic_cmd_name/run."
        fi
        if [ ! -x "$_hic_cmd_dir/run" ]; then
            hw_die "commands/$_hic_cmd_name/run in module '$_hic_name' is not executable" \
                   "Fix with: chmod +x <module-path>/commands/$_hic_cmd_name/run"
        fi

        # Deploy the entire command directory
        _hic_dest_dir="$_hic_gen/commands/$_hic_name/$_hic_cmd_name"
        mkdir -p "$_hic_dest_dir"
        cp -r "$_hic_cmd_dir/." "$_hic_dest_dir/"

        # Generate a PATH-visible launcher
        hw_make_launcher "$_hic_gen/bin/$_hic_cmd_name" "$_hic_dest_dir"
    done
}

# hw_make_launcher launcher_path command_dir
# Write a thin shell wrapper that sets HOMEWORLD_COMMAND_DIR and execs run.
# The launcher is what ends up on PATH; the command dir is where the files live.
hw_make_launcher() {
    _hml_launcher="$1"
    _hml_cmd_dir="$2"

    # Using a here-doc would require bash; printf is POSIX-clean.
    printf '#!/bin/sh\n' > "$_hml_launcher"
    printf '# Generated by homeworld — do not edit\n' >> "$_hml_launcher"
    printf 'export HOMEWORLD_COMMAND_DIR="%s"\n' "$_hml_cmd_dir" >> "$_hml_launcher"
    printf 'exec "%s/run" "$@"\n' "$_hml_cmd_dir" >> "$_hml_launcher"

    chmod +x "$_hml_launcher"
}

# hw_install_packages provider package_list_file
# Install packages from a file, deduplicating first, then invoking the provider once.
hw_install_packages() {
    _hip_provider="$1"
    _hip_file="$2"

    [ -f "$_hip_file" ] || return 0

    # Read packages, strip blanks and comments, sort+uniq to deduplicate
    _hip_packages=$(grep -v '^[[:space:]]*$' "$_hip_file" | grep -v '^[[:space:]]*#' | sort -u)
    [ -n "$_hip_packages" ] || return 0

    hw_log ""
    hw_log "Planning packages through $_hip_provider:"
    printf '%s\n' "$_hip_packages" | while read -r _hip_pkg; do
        hw_log "  $_hip_pkg"
    done
    hw_log ""

    # Build a flat argument list to pass to the package manager
    _hip_pkg_args=$(printf '%s\n' "$_hip_packages" | tr '\n' ' ')

    case "$_hip_provider" in
        pacman)
            # shellcheck disable=SC2086
            pacman -S --needed --noconfirm $_hip_pkg_args
            ;;
        apt)
            # shellcheck disable=SC2086
            apt-get install -y $_hip_pkg_args
            ;;
        dnf)
            # shellcheck disable=SC2086
            dnf install -y $_hip_pkg_args
            ;;
        brew)
            # shellcheck disable=SC2086
            brew install $_hip_pkg_args
            ;;
        *)
            hw_die "unknown package provider: $_hip_provider"
            ;;
    esac
}

# hw_install_module moddir name gen_path platform distro
# Install a single module into the pending generation.
hw_install_module() {
    _him_moddir="$1"
    _him_name="$2"
    _him_gen="$3"
    _him_platform="$4"
    _him_distro="$5"

    _him_path=$(hw_module_get "$_him_moddir" "$_him_name" "path")

    hw_log "  installing $_him_name..."

    # Step 1: copy assets into generation
    hw_install_assets "$_him_moddir" "$_him_name" "$_him_gen"

    # Step 2: copy commands and generate launchers
    hw_install_commands "$_him_moddir" "$_him_name" "$_him_gen"

    # Step 3: run the module's post-install script if present
    _him_install_script="$_him_path/install.sh"
    if [ -f "$_him_install_script" ]; then
        # Expose stable runtime paths. HOMEWORLD_ROOT always points at current/
        # so that configs written during install.sh don't embed pending paths.
        # HOMEWORLD_TARGET_* lets install.sh inspect the in-progress generation.
        _him_hw_root="$(hw_current)"

        # Prepend the pending generation's bin to PATH so commands installed
        # by dependencies in this same run are already available. We also
        # prepend HW_SELF_BIN (set by the main binary to its own directory)
        # so that 'homeworld' is callable from install.sh even when ~/.local/bin
        # isn't on the user's PATH yet.
        _him_self_bin="${HW_SELF_BIN:-}"
        HOMEWORLD_MODULE_ROOT="$_him_path" \
        HOMEWORLD_MODULE_NAME="$_him_name" \
        HOMEWORLD_PLATFORM="$_him_platform" \
        HOMEWORLD_DISTRO="$_him_distro" \
        HOMEWORLD_ROOT="$_him_hw_root" \
        HOMEWORLD_ASSETS="$_him_hw_root/assets" \
        HOMEWORLD_BIN="$_him_hw_root/bin" \
        HOMEWORLD_TARGET="$_him_gen" \
        HOMEWORLD_TARGET_ASSETS="$_him_gen/assets" \
        HOMEWORLD_TARGET_BIN="$_him_gen/bin" \
        PATH="${_him_self_bin:+$_him_self_bin:}$_him_gen/bin:$PATH" \
            sh "$_him_install_script" \
                || hw_die "install.sh failed for module '$_him_name'" \
                          "The generation was not activated — no changes were applied to your system. Fix the error above and run 'homeworld install' again."
    fi
}
