#!/bin/sh
# install.sh — build one pending generation from small resource primitives.

hw_install_assets() {
    _hia_moddir=$1; _hia_name=$2; _hia_gen=$3
    _hia_path=$(hw_module_get "$_hia_moddir" "$_hia_name" path)
    [ -d "$_hia_path/assets" ] || return 0
    for _hia_item in "$_hia_path/assets"/*; do
        [ -e "$_hia_item" ] || [ -L "$_hia_item" ] || continue
        HOMEWORLD_MODULE_ROOT="$_hia_path" hw_asset_add "$_hia_item" "$(basename "$_hia_item")" "$_hia_gen" "$_hia_name"
    done
}

hw_command_add() {
    _hca_source=$1; _hca_name=$2; _hca_gen=$3; _hca_module=$4
    hw_validate_name "$_hca_name" "command name"
    _hca_dest="$_hca_gen/commands/$_hca_module/$_hca_name"
    if [ -d "$_hca_source" ]; then
        [ -f "$_hca_source/run" ] || hw_die "command $_hca_name is missing an executable run file"
        [ -x "$_hca_source/run" ] || hw_die "command $_hca_name run file is not executable"
        hw_copy_resource "$_hca_source" "$_hca_dest"
    else
        [ -f "$_hca_source" ] && [ -x "$_hca_source" ] || hw_die "command source must be an executable file or command directory"
        mkdir -p "$_hca_dest"
        cp "$_hca_source" "$_hca_dest/run" || hw_die "could not stage command"
        chmod +x "$_hca_dest/run"
    fi
    [ ! -e "$_hca_gen/bin/$_hca_name" ] || hw_die "command name conflict: $_hca_name"
    hw_make_launcher "$_hca_gen/bin/$_hca_name" "$_hca_dest"
}

hw_install_commands() {
    _hic_moddir=$1; _hic_name=$2; _hic_gen=$3
    _hic_path=$(hw_module_get "$_hic_moddir" "$_hic_name" path)
    [ -d "$_hic_path/commands" ] || return 0
    for _hic_item in "$_hic_path/commands"/*; do
        [ -d "$_hic_item" ] || continue
        hw_command_add "$_hic_item" "$(basename "$_hic_item")" "$_hic_gen" "$_hic_name"
    done
}

hw_make_launcher() {
    _hml_launcher=$1; _hml_dir=$2
    mkdir -p "$(dirname "$_hml_launcher")"
    {
        printf '#!/bin/sh\n'
        printf '# Generated by Homeworld.\n'
        printf 'export HOMEWORLD_COMMAND_DIR=%s\n' "$(printf "'%s'" "$(printf '%s' "$_hml_dir" | sed "s/'/'\\\\''/g")")"
        printf 'exec "$HOMEWORLD_COMMAND_DIR/run" "$@"\n'
    } > "$_hml_launcher"
    chmod +x "$_hml_launcher"
}

hw_install_packages() {
    _hip_provider=$1; _hip_file=$2
    [ -f "$_hip_file" ] || return 0
    _hip_packages=$(grep -v '^[[:space:]]*$' "$_hip_file" | grep -v '^[[:space:]]*#' | sort -u)
    [ -n "$_hip_packages" ] || return 0
    hw_log "Planning packages through $_hip_provider:"
    printf '%s\n' "$_hip_packages" | while IFS= read -r _hip_package; do hw_log "  $_hip_package"; done
    _hip_args=$(printf '%s\n' "$_hip_packages" | tr '\n' ' ')
    case "$_hip_provider" in
        pacman) sudo pacman -S --needed --noconfirm $_hip_args ;;
        apt) sudo apt-get install -y $_hip_args ;;
        dnf) sudo dnf install -y $_hip_args ;;
        brew) brew install $_hip_args ;;
        *) hw_die "unknown package provider: $_hip_provider" ;;
    esac
}

hw_install_module() {
    _him_moddir=$1; _him_name=$2; _him_gen=$3; _him_platform=$4; _him_distro=$5
    _him_path=$(hw_module_get "$_him_moddir" "$_him_name" path)
    hw_log "  installing $_him_name..."
    hw_install_assets "$_him_moddir" "$_him_name" "$_him_gen"
    hw_install_commands "$_him_moddir" "$_him_name" "$_him_gen"
    _him_script="$_him_path/install.sh"
    [ -f "$_him_script" ] || return 0
    _him_self_bin=${HW_SELF_BIN:-}
    HOMEWORLD_MODULE_ROOT="$_him_path" \
    HOMEWORLD_MODULE_NAME="$_him_name" \
    HOMEWORLD_PLATFORM="$_him_platform" \
    HOMEWORLD_DISTRO="$_him_distro" \
    HOMEWORLD_ROOT="$(hw_current)" \
    HOMEWORLD_BIN="$(hw_current)/bin" \
    HOMEWORLD_TARGET="$_him_gen" \
    HOMEWORLD_TARGET_BIN="$_him_gen/bin" \
    PATH="${_him_self_bin:+$_him_self_bin:}$_him_gen/bin:$PATH" \
        sh "$_him_script" || hw_die "install.sh failed for module $_him_name" \
            "The pending generation was not activated."
}
