FROM archlinux:latest
RUN pacman -Syu --noconfirm git ncurses dash busybox
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /homeworld
COPY . .
RUN sh install.sh
RUN sh tests/run.sh
RUN HOMEWORLD_TEST_SHELL=dash dash tests/run.sh
RUN HOMEWORLD_TEST_SHELL="busybox ash" busybox ash tests/run.sh
