FROM debian:latest
RUN apt-get update && apt-get install -y --no-install-recommends git ncurses-bin dash busybox && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /homeworld
COPY . .
RUN sh install.sh
RUN sh tests/run.sh
RUN HOMEWORLD_TEST_SHELL=dash dash tests/run.sh
RUN HOMEWORLD_TEST_SHELL="busybox ash" busybox ash tests/run.sh
